{ pkgs, config, lib, ... }:

let
  ddcciFix = pkgs.nu.writeScript "niri-monitor-fix-ddcci-nvidia" ''
    sleep 5sec; monitor-fix-ddcci-nvidia
  '';

  # niri has no built in xwayland, xwayland-satellite provides it and DISPLAY has
  # to point at the socket it opens.
  xwaylandDisplay = ":12";

  kdlString = s:
    "\"" + (builtins.replaceStrings [ "\\" "\"" "\n" ] [ "\\\\" "\\\"" "\\n" ] s) + "\"";

  environment = config.home.sessionVariables // {
    XDG_SESSION_TYPE = "wayland";
    DISPLAY = xwaylandDisplay;
  };

  autostart =
    [
      [ "xwayland-satellite" xwaylandDisplay ]
      [ "waybar" ]
      [ "eww" "daemon" ]
      [ "clipboard-daemon" ]
    ]
    ++ (lib.optional
      config.opts.system.hardware.gpu.nvidia.monitorDdcciFixEnable
      [ "${ddcciFix}" ]);

  # The only part of the config that has to come from nix.
  generated = ''
    // Generated by desktop-home.nix, do not edit.

    environment {
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList
      (name: value: "    ${kdlString name} ${kdlString (builtins.toString value)}")
      environment)}
    }

    ${lib.concatMapStringsSep "\n"
      (cmd: "spawn-at-startup ${lib.concatMapStringsSep " " kdlString cmd}")
      autostart}
  '';

  # A broken config would leave the session without one, so niri parses it at
  # build time instead of at login.
  configFile = pkgs.runCommandLocal "niri-config.kdl" { } ''
    cat ${./config.kdl} ${pkgs.writeText "niri-generated.kdl" generated} > $out
    ${lib.getExe' pkgs.niri "niri"} validate -c $out
  '';
in
{
  xdg.configFile."niri/config.kdl".source = configFile;

  home.packages = [
    pkgs.xwayland-satellite
  ];
}
