#!/usr/bin/env bash

cd "$(dirname "$0")"

if command -v nh &> /dev/null
then
    NH_COMMAND="nh"
else
    NH_COMMAND="nix run nixpkgs#nh --"
fi

sudo $NH_COMMAND os switch -R --ask . $@ -- \
    --option extra-substituters "https://cache.nixos.org https://nix-community.cachix.org https://graphite.cachix.org" \
    --option extra-trusted-public-keys "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= graphite.cachix.org-1:B7Il1yMpkquN/dXM+5GRmz+4Xmu2aaCS1GcWNfFhsOo="
